"""Password hashing helpers for the admin user.

Used by the installer to render ``HAL0_ADMIN_PASSWORD_HASH`` for the
Caddyfile (Caddy expects a bcrypt hash from ``caddy hash-password``, not
argon2). Used here only as the in-process equivalent for tests and any
future hal0-internal admin-flow that doesn't want to shell out to Caddy.

Caddy's basic_auth uses bcrypt by default. We expose ``hash_password`` /
``verify_password`` as a thin wrapper around argon2-cffi so any future
hal0-side admin-password verification (e.g. a settings re-prompt) doesn't
have to add a second hashing dependency. The Caddy hash itself is still
generated by ``caddy hash-password`` in installer/install.sh — we don't
re-implement bcrypt here.
"""

from __future__ import annotations

from argon2 import PasswordHasher
from argon2.exceptions import VerifyMismatchError

# Argon2id with the library's defaults — these match OWASP 2024 guidance
# (m=65536 KiB, t=3, p=4) and produce hashes around 20ms on commodity
# hardware. Plenty of cost for a token check; not so much that it pegs a
# CPU during high-RPS Bearer auth (we still cache verified token IDs in
# memory, so the hash cost is paid once per token-presentation, not per
# request).
_HASHER = PasswordHasher()


def hash_password(plaintext: str) -> str:
    """Return an argon2id hash of *plaintext*. Never store the plaintext."""
    if not plaintext:
        raise ValueError("password must be non-empty")
    return _HASHER.hash(plaintext)


def verify_password(hash_str: str, plaintext: str) -> bool:
    """Return True iff *plaintext* matches *hash_str*.

    Catches the typed mismatch exception so callers can branch on a bool
    without importing argon2's exception module.
    """
    if not hash_str or not plaintext:
        return False
    try:
        return _HASHER.verify(hash_str, plaintext)
    except VerifyMismatchError:
        return False
    except Exception:
        # Malformed hash, wrong algorithm marker, library version skew —
        # treat as a non-match rather than crash. The caller surfaces a
        # 401, not a 500, on bad credentials.
        return False


__all__ = ["hash_password", "verify_password"]
