// hal0 v0.3 — MCP servers mock data
// 8 servers: 2 bundled + 4 installed + 1 failed + 1 installing + 1 stopped
// 3 connected clients: Claude Code, Cursor, Claude Desktop

const MCP_HOST_BASE = "https://halo-strix.local";

const MCP_SERVERS = [
  // ── Bundled ──────────────────────────────────────────────────────
  {
    id: "hal0-admin",
    name: "hal0-admin",
    description: "Inspect and supervise this hal0 box — list slots, search models, restart slots, read journal.",
    provider: "hal0",
    bundled: true,
    state: "running",          // running | stopped | failed | installing
    since: "14d 02:11",
    pid: 31204,
    transport: "streamable-http",
    url: `${MCP_HOST_BASE}/mcp/admin`,
    tools: 11,
    resources: 4,
    prompts: 2,
    version: "0.3.0",
    clients: ["claude-code", "cursor"],
    activity: { rpm: 14, lastCall: 2 },
  },
  {
    id: "hal0-memory",
    name: "hal0-memory",
    description: "Cognee-backed recall, write, namespace ops over the operator's personal graph.",
    provider: "hal0",
    bundled: true,
    state: "running",
    since: "14d 02:11",
    pid: 31218,
    transport: "streamable-http",
    url: `${MCP_HOST_BASE}/mcp/memory`,
    tools: 8,
    resources: 0,
    prompts: 1,
    version: "0.3.0",
    clients: ["claude-code", "cursor", "claude-desktop"],
    activity: { rpm: 32, lastCall: 0 },
  },

  // ── Installed (aftermarket) ─────────────────────────────────────
  {
    id: "filesystem",
    name: "filesystem",
    description: "Read, write, and search files inside an allowlisted root. Scoped to /home/operator/projects.",
    provider: "modelcontextprotocol",
    bundled: false,
    state: "running",
    since: "4d 18:42",
    pid: 41882,
    transport: "stdio → http bridge",
    url: `${MCP_HOST_BASE}/mcp/filesystem`,
    tools: 9,
    resources: 1,
    prompts: 0,
    version: "1.2.4",
    clients: ["claude-code"],
    env: { ROOT: "/home/operator/projects", MAX_READ_BYTES: "2000000" },
    activity: { rpm: 8, lastCall: 4 },
  },
  {
    id: "github",
    name: "github",
    description: "Repo browsing, issue + PR ops, code search. OAuth via gh-cli token in keychain.",
    provider: "modelcontextprotocol",
    bundled: false,
    state: "running",
    since: "11d 09:14",
    pid: 38440,
    transport: "streamable-http",
    url: `${MCP_HOST_BASE}/mcp/github`,
    tools: 27,
    resources: 0,
    prompts: 3,
    version: "0.9.1",
    clients: ["claude-code"],
    env: { GH_HOST: "github.com" },
    activity: { rpm: 3, lastCall: 41 },
  },
  {
    id: "postgres",
    name: "postgres",
    description: "Read-only SQL over the lab.db dev cluster. Schema-aware completions, EXPLAIN ANALYZE.",
    provider: "modelcontextprotocol",
    bundled: false,
    state: "running",
    since: "2d 04:55",
    pid: 47102,
    transport: "stdio → http bridge",
    url: `${MCP_HOST_BASE}/mcp/postgres`,
    tools: 5,
    resources: 4,
    prompts: 0,
    version: "0.6.0",
    clients: [],
    env: { DSN: "postgres://reader@10.0.0.4:5432/lab" },
    activity: { rpm: 0, lastCall: null },
  },
  {
    id: "obsidian-vault",
    name: "obsidian-vault",
    description: "Search + create notes in the Obsidian vault at /mnt/vault. Renders wikilinks as resources.",
    provider: "community",
    bundled: false,
    state: "installing",
    progress: 67,
    progressLabel: "pulling deps · uv pip install",
    transport: "stdio",
    url: null,
    tools: null,
    version: "0.4.2",
    clients: [],
    activity: { rpm: 0, lastCall: null },
  },
  {
    id: "brave-search",
    name: "brave-search",
    description: "Web search + summarisation via the Brave Search API.",
    provider: "modelcontextprotocol",
    bundled: false,
    state: "failed",
    since: "—",
    transport: "streamable-http",
    url: `${MCP_HOST_BASE}/mcp/brave-search`,
    tools: 2,
    version: "0.7.0",
    clients: [],
    lastError: {
      ts: "2026-05-23 09:14:22",
      code: "BRAVE_API_KEY_MISSING",
      msg: "Required env var BRAVE_API_KEY is unset. Server exited with code 78 (config error).",
      attempts: 3,
    },
    env: { BRAVE_API_KEY: "" },
    activity: { rpm: 0, lastCall: null },
  },
  {
    id: "timed-reminders",
    name: "timed-reminders",
    description: "Create one-shot or recurring reminders that the agent can schedule and trigger.",
    provider: "community",
    bundled: false,
    state: "stopped",
    since: "stopped 3h ago",
    transport: "stdio",
    url: `${MCP_HOST_BASE}/mcp/timed-reminders`,
    tools: 4,
    version: "0.2.1",
    clients: [],
    note: "Manually disabled · auto-start off",
    activity: { rpm: 0, lastCall: null },
  },
];

// ── Connected clients ──────────────────────────────────────────────
const MCP_CLIENTS = [
  {
    id: "claude-code",
    name: "Claude Code",
    host: "ramekin.lan",
    role: "CLI",
    since: "today 09:22",
    servers: ["hal0-admin", "hal0-memory", "filesystem", "github"],
    activity: { rpm: 22, lastCall: 0 },
  },
  {
    id: "cursor",
    name: "Cursor",
    host: "tritium.lan",
    role: "IDE",
    since: "today 08:01",
    servers: ["hal0-admin", "hal0-memory"],
    activity: { rpm: 9, lastCall: 41 },
  },
  {
    id: "claude-desktop",
    name: "Claude Desktop",
    host: "ramekin.lan",
    role: "App",
    since: "today 13:45",
    servers: ["hal0-memory"],
    activity: { rpm: 4, lastCall: 12 },
  },
];

// ── Catalog (browse view inside install drawer) ────────────────────
const MCP_CATALOG = [
  {
    id: "puppeteer", name: "puppeteer", author: "modelcontextprotocol", verified: true,
    description: "Headless-browser automation. Navigate, scrape, screenshot.",
    tools: 9, stars: 2840, category: "browser",
  },
  {
    id: "sqlite", name: "sqlite", author: "modelcontextprotocol", verified: true,
    description: "Read-only SQL over a single sqlite database file.",
    tools: 4, stars: 1820, category: "data",
  },
  {
    id: "gdrive", name: "google-drive", author: "modelcontextprotocol", verified: true,
    description: "Browse and read documents from a Google Drive account.",
    tools: 6, stars: 1410, category: "files",
  },
  {
    id: "slack", name: "slack", author: "modelcontextprotocol", verified: true,
    description: "Channel + DM read, message send, thread fetch.",
    tools: 8, stars: 990, category: "comms",
  },
  {
    id: "linear", name: "linear", author: "linear-app", verified: true,
    description: "Issue + project ops backed by the Linear GraphQL API.",
    tools: 14, stars: 720, category: "issues",
  },
  {
    id: "exa-search", name: "exa-search", author: "exa-labs", verified: false,
    description: "Neural web search and similarity-based document retrieval.",
    tools: 3, stars: 540, category: "search",
  },
  {
    id: "homeassistant", name: "home-assistant", author: "community", verified: false,
    description: "Control Home Assistant entities — lights, sensors, scenes, automations.",
    tools: 11, stars: 480, category: "iot",
  },
  {
    id: "pi-hole", name: "pi-hole", author: "community", verified: false,
    description: "Inspect blocked queries and toggle groups on your Pi-hole instance.",
    tools: 5, stars: 220, category: "iot",
  },
  {
    id: "kagi", name: "kagi", author: "community", verified: false,
    description: "Search via the Kagi API. Universal, summarize, FastGPT.",
    tools: 4, stars: 180, category: "search",
  },
  {
    id: "kubernetes", name: "kubernetes", author: "manusa", verified: false,
    description: "kubectl-flavoured read access to a cluster. Logs, describe, get.",
    tools: 16, stars: 920, category: "ops",
  },
  {
    id: "datadog", name: "datadog", author: "winor30", verified: false,
    description: "Query metrics, monitors, and logs from a Datadog tenant.",
    tools: 7, stars: 310, category: "ops",
  },
  {
    id: "todoist", name: "todoist", author: "abhiz123", verified: false,
    description: "Create, update, complete tasks in Todoist.",
    tools: 6, stars: 240, category: "productivity",
  },
];

const MCP_CATEGORIES = [
  { id: "all",          label: "All" },
  { id: "files",        label: "Files" },
  { id: "data",         label: "Data" },
  { id: "search",       label: "Search" },
  { id: "browser",      label: "Browser" },
  { id: "comms",        label: "Comms" },
  { id: "issues",       label: "Issues" },
  { id: "ops",          label: "Ops" },
  { id: "iot",          label: "IoT" },
  { id: "productivity", label: "Productivity" },
];

window.MCP_SERVERS = MCP_SERVERS;
window.MCP_CLIENTS = MCP_CLIENTS;
window.MCP_CATALOG = MCP_CATALOG;
window.MCP_CATEGORIES = MCP_CATEGORIES;
window.MCP_HOST_BASE = MCP_HOST_BASE;
